# Generated by Django 3.2.8 on 2021-10-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTestRejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_sent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Czas')),
                ('response_time', models.FloatField(verbose_name='Czas odpowiedzi')),
                ('error_code', models.CharField(max_length=20, verbose_name='Kod błędu')),
                ('response_data', models.TextField(verbose_name='Odpowiedź z serwera')),
            ],
            options={
                'verbose_name': 'Odrzucony test',
                'verbose_name_plural': 'Odrzucone testy',
            },
        ),
        migrations.CreateModel(
            name='BloodTestsPassed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_sent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Czas')),
                ('response_time', models.FloatField(verbose_name='Czas odpowiedzi')),
                ('response_http_code', models.CharField(max_length=3, verbose_name='Kod HTTP odpowiedzi')),
            ],
            options={
                'verbose_name': 'Zatwierdzony test',
                'verbose_name_plural': 'Zatwierdzone testy',
            },
        ),
        migrations.CreateModel(
            name='BloodTestsPassedFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.IntegerField(verbose_name='Id Feedbacku z serwera')),
                ('package_code', models.TextField(verbose_name='Kod paczki')),
                ('result_code', models.CharField(choices=[('A100', 'Ok'), ('A101', 'Indywidualna'), ('B100', 'Darmowa'), ('B101', 'Brak dostępności'), ('B102', 'Brak parametrów'), ('B103', 'Złe dane'), ('B104', 'Nieznany błąd'), ('B105', 'Pacjent niepełnoletni')], max_length=20, verbose_name='Kod wyniku')),
                ('description', models.TextField(null=True, verbose_name='Opis')),
                ('blood_test_passed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='blood_tests.bloodtestspassed')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacki',
            },
        ),
    ]
